import { z } from 'zod'
import type { Activity, Lead, Project, Proposal } from '../types'

const optionalText = z.string().trim().max(5000).optional()
export const leadInputSchema = z.object({ businessName:z.string().trim().min(1).max(160), contactName:z.string().trim().max(160).optional(), niche:z.string().trim().min(1).max(120), source:z.string().trim().min(1).max(120), city:z.string().trim().max(160), publicLink:z.string().trim().max(500).optional(), projectInterest:z.string().trim().min(1).max(160), pipelineStatus:z.enum(['Novo lead','Primeiro contato','Conversando','Reunião marcada','Diagnóstico feito','Proposta enviada','Negociação','Fechado','Perdido','Futuro']), temperature:z.enum(['Quente','Morno','Frio']), priority:z.enum(['Alta','Média','Baixa']), estimatedValue:z.number().finite().min(0).max(10000000), finalValue:z.number().finite().min(0).max(10000000).optional(), paymentStatus:z.enum(['Não se aplica','Pendente','Parcial','Pago']), nextActionDate:z.string().max(10).optional(), nextAction:z.string().trim().max(240).optional(), notes:optionalText, lostReason:z.string().trim().max(500).optional(), closedAt:z.string().optional() })

type Row = Record<string, unknown>
const text = (value: unknown) => typeof value === 'string' ? value : ''
const maybe = (value: unknown) => typeof value === 'string' && value ? value : undefined
const number = (value: unknown) => Number(value ?? 0)

export function leadFromRow(row: Row): Lead { return { id:text(row.id), businessName:text(row.business_name), contactName:maybe(row.contact_name), niche:text(row.niche), source:text(row.source), city:text(row.city), publicLink:maybe(row.public_link), projectInterest:text(row.project_interest), pipelineStatus:text(row.pipeline_status) as Lead['pipelineStatus'], temperature:text(row.lead_temperature) as Lead['temperature'], priority:text(row.priority) as Lead['priority'], estimatedValue:number(row.estimated_value), finalValue:row.final_value == null ? undefined : number(row.final_value), paymentStatus:text(row.payment_status) as Lead['paymentStatus'], nextActionDate:maybe(row.next_action_date), nextAction:maybe(row.next_action), notes:maybe(row.notes), lostReason:maybe(row.lost_reason), createdAt:text(row.created_at), updatedAt:text(row.updated_at), closedAt:maybe(row.closed_at) } }
export function leadToRow(input: Lead | Omit<Lead,'id'|'createdAt'|'updatedAt'>) { const value=leadInputSchema.parse(input); return { business_name:value.businessName, contact_name:value.contactName||null, niche:value.niche, source:value.source, city:value.city, public_link:value.publicLink||null, project_interest:value.projectInterest, pipeline_status:value.pipelineStatus, lead_temperature:value.temperature, priority:value.priority, estimated_value:value.estimatedValue, final_value:value.finalValue??null, payment_status:value.paymentStatus, next_action_date:value.nextActionDate||null, next_action:value.nextAction||null, notes:value.notes||null, lost_reason:value.lostReason||null, closed_at:value.closedAt||null } }

export function activityFromRow(row:Row):Activity { return { id:text(row.id), leadId:text(row.lead_id), title:text(row.title), type:text(row.type) as Activity['type'], description:maybe(row.description), date:text(row.date), time:text(row.time).slice(0,5), status:text(row.status) as Activity['status'], priority:text(row.priority) as Activity['priority'] } }
export function activityToRow(value:Omit<Activity,'id'>|Activity) { return { lead_id:value.leadId||null, title:value.title.trim().slice(0,200), type:value.type, description:value.description?.trim()||null, date:value.date, time:value.time||null, status:value.status, priority:value.priority } }
export function proposalFromRow(row:Row):Proposal { return { id:text(row.id), leadId:text(row.lead_id), projectType:text(row.project_type), planName:text(row.plan_name), value:number(row.value), status:text(row.status) as Proposal['status'], sentAt:maybe(row.sent_at), validUntil:text(row.valid_until), probability:number(row.probability), notes:maybe(row.notes) } }
export function proposalToRow(value:Omit<Proposal,'id'>|Proposal) { return { lead_id:value.leadId, project_type:value.projectType.trim(), plan_name:value.planName.trim(), value:value.value, status:value.status, sent_at:value.sentAt||null, valid_until:value.validUntil||null, probability:Math.min(100,Math.max(0,value.probability)), notes:value.notes?.trim()||null } }
export function projectFromRow(row:Row):Project { return { id:text(row.id), leadId:text(row.lead_id), projectType:text(row.project_type), value:number(row.value), status:text(row.status) as Project['status'], currentStage:text(row.current_stage) as Project['currentStage'], paymentStatus:text(row.payment_status) as Project['paymentStatus'], startedAt:text(row.started_at), deadline:text(row.deadline), notes:maybe(row.notes) } }
export function projectToRow(value:Omit<Project,'id'>|Project) { return { lead_id:value.leadId, project_type:value.projectType.trim(), value:value.value, status:value.status, current_stage:value.currentStage, payment_status:value.paymentStatus, started_at:value.startedAt||null, deadline:value.deadline||null, notes:value.notes?.trim()||null } }
